version: 1
formatters:
    default:
        format: "[%(asctime)s][%(levelname)s][%(module)s] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    app_file:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        level: DEBUG
        filename: app.log
        maxBytes: 5242880 # 5M
        backupCount: 9
    local_file:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        level: DEBUG
        filename: local.log
        maxBytes: 5242880 # 5M
        backupCount: 9
    console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
        stream: ext://sys.stdout
loggers:
    app:
        level: DEBUG
        handlers: [console, app_file]
        propagate: false
    local:
        level: DEBUG
        handlers: [local_file]
        propagate: false